#Config SleepingPlus
# Language of the plugin. (French or English)
language: English
# Do you use the permissions of the plugin?
permissions: false
# Effects when the player becomes tired.
# Identified by name, for how long, in seconds, the rate of fatigue so that the effect is activated.
potionsEffect: SLOW,10,30/SLOW_DIGGING,10,40/BLINDNESS,10,60
# Time when the plugin triggers. (Does not work for now, will work in version 1.3)
hourActive: 16000
# Time when the plugin stops. (Does not work for now, will work in version 1.3)
hourDesactive: 1000
# A period to indicate the number of seconds without sleep, the fatigue rate increases by 1 after this time.
timeNoSleep: 20
# The number of minutes it takes being offline for fatigue removed.
timeExitServer: 10
# Number of seconds where you must stay in bed.
timeInBed: 15
# Number of fatigue which will be added at the rate of fatigue in a death.
nbRateWithDeath: 10
# Would you use the xp bar to show the number of fatigue?
useXpBar: false